[package]
name = "passbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.0"
gpgme = "0.11.0"
wl-clipboard-rs = "0.7.0"
